package com.ssafy.e206.errorCode;

public enum ErrorCode {
  NOT_FOUND("NOT_FOUND"),
  METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
  INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
  BAD_REQUEST("BAD_REQUEST"),
  UNAUTHORIZED("UNAUTHORIZED"),
  FORBIDDEN("FORBIDDEN"),
  CONFLICT("CONFLICT"),
  GONE("GONE"),
  PRECONDITION_FAILED("PRECONDITION_FAILED"),
  TOO_MANY_REQUESTS("TOO_MANY_REQUESTS"),
  REQUEST_TIMEOUT("REQUEST_TIMEOUT"),
  UNPROCESSABLE_ENTITY("UNPROCESSABLE_ENTITY"),
  LOCKED("LOCKED"),
  FAILED_DEPENDENCY("FAILED_DEPENDENCY"),
  UPGRADE_REQUIRED("UPGRADE_REQUIRED"),
  PRECONDITION_REQUIRED("PRECONDITION_REQUIRED"),
  TOO_EARLY("TOO_EARLY"),
  TOO_LATE("TOO_LATE"),
  UNAVAILABLE_FOR_LEGAL_REASONS("UNAVAILABLE_FOR_LEGAL_REASONS"),
  NOT_EXTENDED("NOT_EXTENDED"),
  NETWORK_AUTHENTICATION_REQUIRED("NETWORK_AUTHENTICATION_REQUIRED"),
  SERVICE_UNAVAILABLE("SERVICE_UNAVAILABLE"),
  GATEWAY_TIMEOUT("GATEWAY_TIMEOUT"),
  HTTP_VERSION_NOT_SUPPORTED("HTTP_VERSION_NOT_SUPPORTED"),
  VARIANT_ALSO_NEGOTIATES("VARIANT_ALSO_NEGOTIATES"),
  INSUFFICIENT_STORAGE("INSUFFICIENT_STORAGE"),
  LOOP_DETECTED("LOOP_DETECTED"),
  NOT_IMPLEMENTED("NOT_IMPLEMENTED");
  // INVALID_INPUT_VALUE(400, "Invalid Input Value"),
  // ENTITY_NOT_FOUND(400, "Entity Not Found"),
  // INVALID_JWT_TOKEN(401, "Invalid JWT Token"),
  // EXPIRED_JWT_TOKEN(401, "Expired JWT Token"),
  // ACCESS_DENIED(401, "Access Denied"),
  // METHOD_NOT_ALLOWED(405, "Method Not Allowed"),
  // INTERNAL_SERVER_ERROR(500, "Server Error"),
  // HANDLE_ACCESS_DENIED(403, "Access is Denied"),
  // NOT_FOUND(404, "Not Found"),
  // REQUEST_URI_TOO_LONG(414, "Request URI Too Long"),
  // NULL_POINRTER(6000, "널이지롱");

  private final String exception;

  ErrorCode(final String exception) {
    this.exception = exception;
  }

  public String getMessage() {
    return this.exception;
  }
}